### ISSUE TITLE
v. 1.5.2 isn't pushed to npmjs.org

### ISSUE THREAD

**Issue by toredash** [SocketCluster/sc-cluster-broker-server#2]
https://www.npmjs.com/package/scc-broker

V 1.5.1 is the latest present, 1.5.2 is available

**Comment by jondubois** [comment]
@toredash The scc-broker and scc-state images don't actually need to be on npm for it to work; only the dependencies when building the docker images come from npm. I published the repos to npm to prevent other people from taking the package names and creating confusion.

**Comment by toredash** [comment]
thanks for pointing it out
