### ISSUE TITLE
Undefined handshake

### ISSUE THREAD

**Issue by happilymarrieddad** [SocketCluster/sc-cluster-broker-server#6]
Hey,

When you clone the repo and add a AUTH_KEY it fails to add the handshake. Here is the code

Which one should I use? WS or SC?

```
 if (AUTH_KEY) {
      scServer.addMiddleware(scServer.MIDDLEWARE_HANDSHAKE, (req, next) => {
        var urlParts = url.parse(req.url, true);
        if (urlParts.query && urlParts.query.authKey == AUTH_KEY) {
          next();
        } else {
          var err = new Error('Cannot connect to the cluster broker server without providing a valid authKey as a URL query argument.');
          err.name = 'BadClusterAuthError';
          next(err);
        }
      });
    }

```

![selection_034](https://user-images.githubusercontent.com/6416323/37366940-90dcf98e-26c7-11e8-8918-fae46d9cb2cf.png)

**Comment by happilymarrieddad** [comment]
I would make a pull request but I'm not sure which one to add

**Comment by jondubois** [comment]
@happilymarrieddad Nice find! It's `MIDDLEWARE_HANDSHAKE_WS` - That's the new name for `MIDDLEWARE_HANDSHAKE`.

**Comment by happilymarrieddad** [comment]
@jondubois I created a pull request to fix it. Thanks!
