### ISSUE TITLE
Which one does the work?

### ISSUE THREAD

**Issue by happilymarrieddad** [SocketCluster/sc-cluster-broker-server#8]
@jondubois hey man, 

On the scc-broker, which one (worker,broker) does the work? Basically, we have an scc-broker instance on a 4 core machine. I'm wondering if I should do ```worker:4``` or ```broker:4``` or ```worker:2,broker:2```.

**Comment by jondubois** [comment]
@happilymarrieddad In the case of scc-broker, both worker and broker processes share the work of aggregating channel data and distributing it to user-facing SC instances (roughly equally).

**Comment by happilymarrieddad** [comment]
@jondubois so with a 4 core system I should be setting it to worker:2,broker:2 ?

**Comment by jondubois** [comment]
@happilymarrieddad It depends on how much pub/sub your system does. If it does a lot of pub/sub then maybe 3 workers, 1 broker is better. If it does no pub/sub at all, then 4 workers, 1 broker.

**Comment by jondubois** [comment]
If you have no idea and workload can change over time, then 4 workers, 4 brokers.

**Comment by happilymarrieddad** [comment]
@jondubois Almost everything is sub/pub.. Thanks!
